### ISSUE TITLE
Recipe Lookup

### ISSUE THREAD

**Issue by StevieShibly8** [zaidi-01/PantryPal#10]
- [ ] User should be able to search for a recipe
- [ ] User should be able to filter recipe results
- [ ] User should be able to sort recipe results
- [ ] User should be able to view recipe details
